In [86]:
import numpy as np

In [87]:
my_list = [1,2,3,4,5,6,]
arr = np.array(my_list)
print(arr)
print(my_list)

[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]


In [88]:
arr = np.arange(start= 1,stop= 10,step= 1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [89]:
arr = np.linspace(start=1,stop=100,num=100)
print(arr)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]


In [6]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
arr = np.full(shape=)#atributo del array que es el tamaño,continua abajo:

SyntaxError: expected argument value expression (732395115.py, line 1)

In [9]:
arr.shape

(10,)

In [10]:
arr = np.full(shape=(4,2), fill_value=7)
print(arr)

[[7 7]
 [7 7]
 [7 7]
 [7 7]]


O sea, aca arriba crea un array bidimensional de dos dimensiones(marcado por el doble corchete[[]]) y si hago:

In [13]:
print(arr.shape)# Nos dice que tiene 4 x 2, 4 filas por 2 colomnas

(4, 2)


In [15]:
base = np.full(shape=(2,6), fill_value=4.41)# Array de dimension 2,6 y los valores van a ser 4,41
print(base)
print(np.full_like(base, 5))

[[4.41 4.41 4.41 4.41 4.41 4.41]
 [4.41 4.41 4.41 4.41 4.41 4.41]]
[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


O sea, rellena un nuevo array que copiando la cantidad de elemtos del shake(las 2 filas con 6 columnas y las va a rellenar con el valor asignado luego de la palabra base)

In [16]:
base = np.full(shape=(2,6), fill_value=4.41)# Array de dimension 2,6 y los valores van a ser 4,41
print(base)
print(np.full_like(base, np.pi))

[[4.41 4.41 4.41 4.41 4.41 4.41]
 [4.41 4.41 4.41 4.41 4.41 4.41]]
[[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]]


En lo anterior cambiamos el valor de 5 por el valor de pi, ya que la libreria tambien lo tiene

# Crear Arrays con numeros aleatorios

In [23]:
arr = np.random.rand(4,2)
print(arr)

[[0.66240146 0.52596896]
 [0.77924985 0.70627153]
 [0.45151778 0.94665824]
 [0.24155659 0.63370145]]


cada vez que renderizo, me da numeros aleatorios, sin poner negativos

In [25]:
arr = np.random.randint(4,2)
print(arr)

ValueError: low >= high

A lo anterior el profesor TAMPOCO lo resolvio

In [38]:
arr = np.random.uniform(low=0, high=10, size=(2,2))
print(arr)

[[1.52902787 3.96268438]
 [4.97849813 6.740047  ]]


En lo anterior le pongo desde que numero hasta que numero quiero que sea el random...

In [39]:
#Trabajando con numeros negativos:
arr = np.random.randn(4,2)
print(arr)

[[ 1.44615558 -2.30013787]
 [ 0.15691629  0.15025233]
 [ 0.61296144 -0.40025598]
 [ 1.68562744  0.30544285]]


Arriba a veces tenemos numeros negativos y otras no... depende del random, pero lo importante es que han aparecido los negativos

In [47]:
# Distribucion Normal
arr = np.random.normal(loc=5, scale=1, size=6)#el cual es un array unidimensional scale es la desviacion standar
print(arr)

[7.03267988 3.68165166 2.44833406 4.71973711 6.26107763 4.27482551]


# Tamańo de Arrays

In [50]:
arr = np.zeros(9)
print(arr.shape)
print(arr)

(9,)
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [52]:
#supongamos que queremos que, en vez de 9 elementos, queremos que sea de 3x3, creando una nueva matriz
b = np.reshape(arr,[3,3])
print(b)
print(b.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


Atencion, en lo anterior no puedo pretender que un array de 9 elementos este en un 2 x 3, ya que no va a dar... debe ser de 3 x 3 elementos...Debe ser uniforme

In [53]:
print(b.shape)# o sea: forma.-

(3, 3)


In [75]:
# 25,54 Lo que hace "arange" es colocar los numeros ordenados(si va solo es tácito, si son dos de tal a tal en un array), por ejemplo:
matrix = np.arange(5)
print(matrix)
matrix = np.arange(8, 15)
print(matrix)
# y a "arange" le agregamos "reshape para que cree las filas y columnas"
matrix = np.arange(16).reshape(4,4)
print(matrix)#buscar en google que es arange

[0 1 2 3 4]
[ 8  9 10 11 12 13 14]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


# Slicing con arrays

In [60]:
print(matrix[0])#con esto accedo a la primer fila

[0 1 2 3]


In [57]:
print(matrix[0,1])#Aca le pido que me de lo que esta en fila 0, columna 1, el cual es el 1...

1


In [64]:
#27,46. Acceder solo a una columna
print(matrix[:,2])
#Para que ésto funcione, NO OLVIDAR de colocar los dos puntos(:) antes de la coma (,)

[ 2  6 10 14]


# Copiar arrays

In [65]:
matrix_b = matrix #y ya esta copiado
print(matrix)
print(matrix_b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Para comprobar que son iguales, lo probamos a traves del id:

In [67]:
#30,52
print(id(matrix))
print(id(matrix_b))
# o sea, tienen la misma porción de memoria, estan apuntando al mismo lugar, pero lo que queremos es hacer una copia para trabajar por separado, para ello np tiene .copy:

4492637840
4492637840


In [69]:
matrix_b = matrix.copy()
print(matrix)
print(matrix_b)
#aca vemos que son iguales...peeero:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [71]:
#si le pedimos el id:
print(id(matrix))
print(id(matrix_b))
#ya vemos que el lugar que ocupan en memoria ya son diferentes, por lo tanto, todo lo que haga en uno NO AFECTA en el otro...

4492637840
4369778704


#Operaciones con arrays (32,52)
En Numpay

In [76]:
a = np.arange(5,10)
print(a)

[5 6 7 8 9]


In [78]:
#sumar la cantidad 10:
print(a + 10)
# o sea, lo hace con CADA UNO de los elementos

[15 16 17 18 19]


In [79]:
#resta:
print(a - 10)
#hace lo mismo pero inverso a la suma

[-5 -4 -3 -2 -1]


In [81]:
#34,27
b = np.full(4,3)#o sea: de tamaño 4 y lleno de 3...
c = np.ones(4, dtype='int')#el dtype es un atributo que marca el tipo de elemento que van a contener sus datos
print(b)
print(c)

[3 3 3 3]
[1 1 1 1]


In [82]:
print(b - c)

[2 2 2 2]


In [83]:
print(b + c)

[4 4 4 4]


Multiplicaciones:
Utilizaremos una funcion que se llama np.matmul

In [84]:
#35,50
#para multiplicar deben coincidir las filas y columnas de los arrays:
print(np.matmul(b,c))

12


In [91]:
#36,54
a = np.array([[2,3],[2,3],[2,3]])
b = np.array([[1,6,5,2,7],[1,2,7,0,9]])

print(a)
print(b)

[[2 3]
 [2 3]
 [2 3]]
[[1 6 5 2 7]
 [1 2 7 0 9]]


In [92]:
np.matmul(a,b)
#devuelve un array con la multiplicacion de cada uno de los elementos

array([[ 5, 18, 31,  4, 41],
       [ 5, 18, 31,  4, 41],
       [ 5, 18, 31,  4, 41]])

In [93]:
#Tambien tenemos otra forma de hadder multiplicaciones:
print(a@b) #y Voila... ahorra tener que ponerle matmul y todo eso...

[[ 5 18 31  4 41]
 [ 5 18 31  4 41]
 [ 5 18 31  4 41]]


In [96]:
#Transpuesta: intercambia las filas por las columnas 38,00
print(a)
print('-'*15)
print(a.T)#"T" este es el metodo de la transpuesta


[[2 3]
 [2 3]
 [2 3]]
---------------
[[2 2 2]
 [3 3 3]]


In [97]:
#38,53
a = np.arange(4)
print(a)

[0 1 2 3]


In [98]:
#Divisiones:
print(a / 2)
print(a // 2)

[0.  0.5 1.  1.5]
[0 0 1 1]


In [99]:
#Potenciaciones: 39,48
print(a ** 2
      )

[0 1 4 9]


In [100]:
#Invertir los numeros en negativos:
print(-a)

[ 0 -1 -2 -3]


In [101]:
#Resto de la Division:
print(a % 2)

[0 1 0 1]


# Estadistica: 40,39

In [105]:
#Supongamos que tenemos una lista de alumnos con su altura, y tenemos que hacer un EDA:(Analisis exploratorio y estadistica)
# a la lista la vamos a trabajar como lista, no como array:
heigh_list = [1.70,1.85,1.90,1.65,1.48,1.75,1.69,1.84,1.73,1.79,1.62,1.59]


In [107]:
# la media nos va a devolver la sumatoria de cada uno de estos elementos, dividida por la cantidad de elementos totales:
print(np.mean(heigh_list))

1.7158333333333333


In [111]:
#42m15 ahra la mediana, que es el punto medio de nuestros  elementos
print(np.median(heigh_list))
# o sea: el PUNTO MEDIO de nuestros elementos, aca si saca un promedio

1.7149999999999999


In [112]:
# Tambien tenemos la desviacion estandar, para saber que tan dispersos estan nuestros datos:
print(np.std(heigh_list))

0.11550312646081155


In [113]:
# y el percentil, o sea devuelve el percentil quésimo de los datos, a lo largo de un eje especificado:
print(np.percentile(heigh_list, q=90))#Este valor debe estar entre 0 y 100 

1.8490000000000002


In [114]:
# valor exponencial de una lista:
print(np.exp(heigh_list))

[5.47394739 6.35981952 6.68589444 5.20697983 4.39294568 5.75460268
 5.41948071 6.29653826 5.64065391 5.98945247 5.05309032 4.90374893]


In [115]:
#Logaritmo "natural"
print(np.log(heigh_list))
# obvio para cada uno de los elementos

[0.53062825 0.61518564 0.64185389 0.50077529 0.39204209 0.55961579
 0.52472853 0.60976557 0.54812141 0.58221562 0.48242615 0.46373402]


In [116]:
# Raiz Cuadrada:
print(np.sqrt(heigh_list))
# Tambien para cada uno de los elementos

[1.30384048 1.36014705 1.37840488 1.28452326 1.21655251 1.32287566
 1.3        1.356466   1.31529464 1.33790882 1.27279221 1.26095202]


In [117]:
# 45,14
#Funcion que compara si los elementos son mayores o no, devuelve booleanos:
a = np.random.uniform(low=1.9, high=2.0, size=12)
b = np.random.uniform(low=1.4, high=2.0, size=12)
print(a)
print(b)

[1.95110375 1.95274239 1.92741245 1.94304479 1.99647638 1.94303754
 1.98133867 1.98590175 1.97700998 1.91035727 1.9770088  1.93232699]
[1.63945592 1.66289368 1.41833916 1.61182097 1.75278755 1.59568745
 1.92382968 1.96968545 1.70897638 1.88662357 1.81425908 1.87587318]


In [119]:
# 46,35
np.greater(a, b)
# y aca devuelve si a es > que b y viceversa

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [121]:
# Y asi entramos al tema de las mascaras, con las cuales manipulamos y seleccionamos elementos de un subconjunto en un array que tengan ciertas condiciones, ciertos filtros. O sea: es una matriz booleana cuyos elementos deben corresponder con el elemento original, la mascara va a ser del mismoo tamaño, del mismo shape, y solo se ve cambiado el T o F:
arr = np.arange(0,20).reshape(2,10)
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [123]:
# Ver solo los pares:para ello razonamos que, sabiendo que par o impar es todo numero cuyo resto de 2 da 0 ó 1...
mask = ((arr % 2))  == 0
# por lo tanto el resultado sera T o F, de acuerdo si son pares o no...
print(mask)

[[ True False  True False  True False  True False  True False]
 [ True False  True False  True False  True False  True False]]


In [124]:
# 49,35
# pero me da T o F, sin embargo QUEREMOS VER los elementos, para ello indexamos:
print(arr[mask])
# y asi devuelve SOLO LOS VALORES que responden afirmativamente a la consigna dada

[ 0  2  4  6  8 10 12 14 16 18]


In [125]:
# Tambien puedo armar la "mascara" adentro de print:
print(arr[((arr % 2) == 1)])
# pero es mas entendible el anterior

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# 50.30
# Todas las mascaras funcionan con todo los operadores

Pista de la tarea: 
Ejercicio 4 hacer slicing